#!/bin/bash

# Define the packages
packages=(
    "@eslint/js --save-dev"
    "@types/bcrypt --save-dev"
    "@types/cors --save-dev"
    "@types/express --save-dev"
    "@types/jsonwebtoken --save-dev"
    "@types/morgan --save-dev"
    "@types/node --save-dev"
    "@typescript-eslint/eslint-plugin --save-dev"
    "@typescript-eslint/parser --save-dev"
    "cross-env --save-dev"
    "eslint --save-dev"
    "eslint-config-love --save-dev"
    "eslint-config-prettier --save-dev"
    "eslint-plugin-prettier --save-dev"
    "globals --save-dev"
    "husky --save-dev"
    "morgan --save-dev"
    "prettier --save-dev"
    "rimraf --save-dev"
    "ts-node-dev --save-dev"
    "typescript --save-dev"
    "bcrypt"
    "cors"
    "dotenv"
    "express"
    "express-rate-limit"
    "jsonwebtoken"
    "zod"
)